// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wntuvobvtdjtrlzrkghp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndudHV2b2J2dGRqdHJsenJrZ2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNjM0MjUsImV4cCI6MjA3MTgzOTQyNX0.__60JUWlEKzDVHEcfvbmIVi_pGvRdxfDCtmLha7aF1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});